# Generated by Django 5.1.1 on 2024-10-10 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('calorie', models.PositiveSmallIntegerField()),
                ('kilojoule', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('NONE', '-'), ('ROOT', 'Root'), ('STEM', 'Stem'), ('BULB', 'Bulb'), ('LEAF', 'Leaf'), ('FRUIT', 'Fruit'), ('FLOWER', 'Flower'), ('SEED', 'Seed'), ('TUBER', 'Tuber')], default='None', max_length=20)),
                ('wiki', models.URLField(null=True)),
            ],
        ),
    ]
