# Generated by Django 5.1.1 on 2024-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('calorie', models.PositiveSmallIntegerField()),
                ('kilojoule', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('None', '-'), ('Root', 'Root vegetables'), ('Stem', 'Stem vegetables'), ('Bulb', 'Bulb vegetables'), ('Leaf', 'Leaf vegetables'), ('Fruit', 'Fruit vegetables'), ('Flower', 'Flower vegetables'), ('Seed', 'Seed vegetables'), ('Tuber', 'Tuber vegetables')], default='None', max_length=20)),
                ('wiki', models.URLField(null=True)),
            ],
        ),
    ]
