# Generated by Django 5.1.1 on 2024-10-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='category',
            field=models.CharField(choices=[('NONE', '-'), ('ROOT', 'Root'), ('STEM', 'Stem'), ('BULB', 'Bulb'), ('LEAF', 'Leaf'), ('FRUIT', 'Fruit'), ('FLOWER', 'Flower'), ('SEED', 'Seed'), ('TUBER', 'Tuber')], default='None', max_length=20),
        ),
    ]
