# Generated by Django 5.1.1 on 2024-10-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0002_alter_vegetable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
