# Generated by Django 5.1.1 on 2024-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0002_alter_vegetable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
