# Generated by Django 5.1.1 on 2024-10-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0003_vegetable_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='cover',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
