# Generated by Django 5.1.1 on 2024-10-17 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0005_alter_vegetable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
